_target_: optispeech.model.generator.modules.Conformer
_partial_: true
attention_dim: 256
attention_heads: 2
linear_units: 1024
num_blocks: 4
dropout_rate: 0.2
positional_dropout_rate: 0.2
attention_dropout_rate: 0.2
normalize_before: true
concat_after: false
positionwise_layer_type: conv1d
positionwise_conv_kernel_size: 1
macaron_style: true
pos_enc_layer_type: rel_pos
selfattention_layer_type: rel_selfattn
activation_type: swish
use_cnn_module: True
cnn_module_kernel: 7
zero_triu: False
init_type: xavier_uniform
