defaults:
  - _self_
  - generator: default
  - discriminator: vocos_disc
  - optimizer: adamw
  - scheduler: cosine_with_warmup
  - vocoder: wavenext

_target_: optispeech.model.OptiSpeech
dim: 256
train_args:
  cache_generator_outputs: true
  gradient_clip_val: 10
  gradient_accumulate_batches: null
  pretraining_steps: 1000
  evaluate_periodicity: true
  evaluate_utmos: true
  evaluate_pesq: true
data_args:
  name: ${data.name}
  num_speakers: ${data.num_speakers}
  text_processor: ${data.text_processor}
  feature_extractor: ${data.feature_extractor}
  batch_size: ${data.batch_size}
  data_statistics: ${data.data_statistics}
inference_args:
  d_factor: 1.1
  p_factor: 1.6
  e_factor: 1.2
