_target_: optispeech.model.generator.PitchPredictor
_partial_: true
num_layers: 2
intermediate_dim: 384
kernel_size: 3
dropout: 0.5
embed_kernel_size: 9
embed_dropout: 0.5
conv_layer_class:
  _target_: torch.nn.Conv1d
  _partial_: true
